# `cargo-deny` configuration.

feature-depth = 1

[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "warn"
severity-threshold = "Medium"

[licenses]
unlicensed = "deny"
allow = [
  # Permissive open-source licenses
  "MIT",
  "Apache-2.0",
  "BSD-3-Clause",
  "Unicode-DFS-2016",
]
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip = [
  # Old version used by `gloo` crates; hopefully, will updated soon
  { name = "serde-wasm-bindgen", version = "^0.5" },
]
skip-tree = [
  # Build dependency that produces several multiple versions
  { name = "toml", version = "^0.8" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = [
  # Allow depending on a git version of the "main" dependency
  "https://github.com/slowli/elastic-elgamal.git",
]
