[build]
publish = "dist/"
command = "bash ./build.sh"

[build.environment]
NODE_VERSION = "16.13.0"
RUST_VERSION = "1.58.1"

# Rewrite rule to enable history-based navigation
[[redirects]]
from = "/*"
to = "index.html"
status = 200
