[build]
publish = "dist/"
command = "bash ./build.sh"

[build.environment]
NODE_VERSION = "20.11.0"
RUST_VERSION = "1.80.0"

# Rewrite rule to enable history-based navigation
[[redirects]]
from = "/*"
to = "index.html"
status = 200
