name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: latest
      - name: Install cargo-deny
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-deny
          version: "^0.14"

      - run: npm ci

      # Rust-related lints
      - name: Format Rust code
        run: "npm run lint:fmt"
      - name: Clippy
        run: cargo clippy --all-features --all-targets -- -D warnings
      - name: Check Rust dependencies
        run: cargo deny check

      # Tests
      - name: Test JS wrapper
        run: "npm run test:js"
      - name: Test WASM
        run: "npm run test:wasm -- --chrome --firefox --all-features"

      # Build intermediate artifact & check that the Webpack build works.
      - name: Build website
        run: "npm run build"

      # Frontend lints
      - name: Lint JS code
        run: "npm run lint:js"
      - name: Lint styles
        run: "npm run lint:scss"
